name: Generate sitemap 

on:
  push:
    branches: [ main ]
    paths: [ '**.html' ]

jobs:
  sitemap_job:
    runs-on: ubuntu-latest
    name: Generate a sitemap
    steps:
    - name: Checkout the repo
      uses: actions/checkout@v3
      with:
        fetch-depth: 0 
    
    - name: Generate the sitemap
      id: sitemap
      uses: cicirello/generate-sitemap@v1
      with:
        base-url-path: https://www.cancionerocatolico.cl/
    
    - name: Output stats
      run: |
        echo "sitemap-path = ${{ steps.sitemap.outputs.sitemap-path }}"
        echo "url-count = ${{ steps.sitemap.outputs.url-count }}"
        echo "excluded-count = ${{ steps.sitemap.outputs.excluded-count }}"
    
    - name: Commit sitemap changes
      uses: EndBug/add-and-commit@v9
      with:
        author_name: Vincent A. Cicirello
        author_email: cicirello@users.noreply.github.com
        message: "Automated sitemap update."
        add: "sitemap.xml"
